version: '3'
services:

  db:
    image: mongo:4.2.8
    container_name: db
    ports:
      - "4000:27017"
    restart: always

  azure-storage:
    image: azure-storage
    build:
      context: ./azure-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=<your storage account>
      - STORAGE_ACCESS_KEY=<your storage access key>
    restart: "no"

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    depends_on:
      - db
    restart: "no"
  
history:
  image: history
  build:
    context: ./history
    dockerfile: Dockerfile-dev
  container_name: history

  volumes:
    - /tmp/history/npm-cache:/root/.npm:z # share npm cache from host to container to speed up npm installs
    - ./history/src:/usr/src/app/src:z    # share source code directly from host to the container

  ports:
    - "4002:80"
  environment:
    - PORT=80
    - NODE_ENV=development
  restart: "no"