version: '3'
service:
  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
      container_name: video-streaming
      ports:
        -"4000:80"
      environment:
        - PORT=80
      restart: "no"
